api.env=Local

# Database
spring.datasource.url=jdbc:oracle:thin:@45.114.141.87:2601:USITORADB
spring.datasource.username=ENC(AvlkQfdEZdRf473QF0JA2ZaT8CAj2YOBjFGzhXVcvS/VD57PwFuPQGXE6SL9DdFX)
spring.datasource.password=ENC(oQisfgfLJXZL6R7f09OLbzu+jvEn1bTss9OpnBw0AJZbnnc7cD3IbaTr6VZQXWeC)

# Spring Boot Admin
spring.boot.admin.client.instance.service-base-url=http://localhost:6004
spring.boot.admin.client.url=http://localhost:6001

# Eureka
eureka.client.service-url.defaultZone=http://localhost:5999/serviceregistry/eureka/

# OAuth2
spring.security.oauth2.client.registration.google.redirectUri=http://localhost:5004/oauth2/callback/{registrationId}
app.oauth2.authorizedRedirectUris[0]=http://localhost:4200/oauth2
