api.env=Local

# DB - Main
spring.datasource.main.jdbc-url=jdbc:oracle:thin:@45.114.141.87:2601:USITORADB
spring.datasource.main.username=ENC(AvlkQfdEZdRf473QF0JA2ZaT8CAj2YOBjFGzhXVcvS/VD57PwFuPQGXE6SL9DdFX)
spring.datasource.main.password=ENC(oQisfgfLJXZL6R7f09OLbzu+jvEn1bTss9OpnBw0AJZbnnc7cD3IbaTr6VZQXWeC)
spring.datasource.main.driver-class-name=oracle.jdbc.OracleDriver

# DB - SAP
spring.datasource.sap.jdbc-url=jdbc:oracle:thin:@45.114.141.87:2601:USITORADB
spring.datasource.sap.username=ENC(IBMFcCN7CVMNSliyQUpRmL+7cCqDhOarxWCsyHh45oVPuao13RHF7GlcHbOBohfE)
spring.datasource.sap.password=ENC(ji/M1e0key8SLpfIQ34lm1WFU1pKKYXFWVqJ36N2yHwyKkgq4OKJ13b7RhxpUGy8)
spring.datasource.sap.driver-class-name=oracle.jdbc.OracleDriver

# DB - MES
spring.datasource.mes.jdbc-url=jdbc:oracle:thin:@45.114.141.87:2601:USITORADB
spring.datasource.mes.username=ENC(axPUCYKTuWjYuqTPp7qcWMD803Jo0Jm9Zu+SQN5bQaFyW1BcpZFGiog+uRjDBqat)
spring.datasource.mes.password=ENC(GrAREUc59Wvvs5SZK/DH1KIynZK0KfrsB3BJDLJtWhGuOx+lQQEBra1xUf2V9D+e)

# DB - Remote MES
spring.datasource.remotemes.jdbc-url=jdbc:oracle:thin:@45.114.141.87:2601:USITORADB
spring.datasource.remotemes.username=ENC(axPUCYKTuWjYuqTPp7qcWMD803Jo0Jm9Zu+SQN5bQaFyW1BcpZFGiog+uRjDBqat)
spring.datasource.remotemes.password=ENC(GrAREUc59Wvvs5SZK/DH1KIynZK0KfrsB3BJDLJtWhGuOx+lQQEBra1xUf2V9D+e)
spring.datasource.remotemes.driver-class-name=oracle.jdbc.OracleDriver

# Spring Boot Admin
spring.boot.admin.client.instance.service-base-url=http://localhost:6009
spring.boot.admin.client.url=http://localhost:6001

# Eureka
eureka.client.service-url.defaultZone=http://localhost:5999/serviceregistry/eureka/

# Socket.IO
yms.socket.hostname=localhost
yms.socket.webHost=localhost
yms.socket.socketServer=localhost
yms.socket.port.rfid=6018
yms.socket.port.mesPort=6013
