server.port=6888

spring.application.name=FLUENTA-SYMS-API-GATEWAY

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.security=DEBUG

spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true

spring.main.web-application-type=reactive

# Gateway Routes
spring.cloud.gateway.routes[0].id=Fluenta-SYMS-Auth-Service
spring.cloud.gateway.routes[0].uri=lb://Fluenta-SYMS-Auth-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/oauth2/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# Eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
